using System.Text;

namespace ZktecoRelay.Manager;

internal static class EnvSettings
{
    public static string GetAppDataEnvPath()
    {
        return Path.Combine(
            Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),
            "ZktecoRelay",
            ".env");
    }

    public static string ResolveWritePath()
    {
        var appDataEnv = GetAppDataEnvPath();

        // 1. If AppData .env already exists, keep writing to AppData .env
        if (File.Exists(appDataEnv))
        {
            return appDataEnv;
        }

        // 2. Check if AppContext.BaseDirectory is writable
        var baseDir = AppContext.BaseDirectory;
        if (IsDirectoryWritable(baseDir))
        {
            return Path.Combine(baseDir, ".env");
        }

        // 3. Check if parent directory is writable (e.g. {app} when manager is in {app}\manager)
        var parentDir = Path.GetDirectoryName(baseDir.TrimEnd(Path.DirectorySeparatorChar, Path.AltDirectorySeparatorChar));
        if (!string.IsNullOrEmpty(parentDir) && IsDirectoryWritable(parentDir))
        {
            return Path.Combine(parentDir, ".env");
        }

        // 4. Fallback to AppData .env
        var appDataDir = Path.GetDirectoryName(appDataEnv)!;
        Directory.CreateDirectory(appDataDir);
        return appDataEnv;
    }

    public static Dictionary<string, string> ReadResolved(out string loadedPath)
    {
        var candidates = new[]
        {
            GetAppDataEnvPath(),
            Path.Combine(AppContext.BaseDirectory, ".env"),
            Path.Combine(AppContext.BaseDirectory, "..", ".env"),
            Path.Combine(Directory.GetCurrentDirectory(), ".env")
        };

        foreach (var path in candidates)
        {
            var fullPath = Path.GetFullPath(path);
            if (File.Exists(fullPath))
            {
                loadedPath = fullPath;
                return Read(fullPath);
            }
        }

        loadedPath = ResolveWritePath();
        return new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
    }

    public static bool IsDirectoryWritable(string directoryPath)
    {
        try
        {
            if (!Directory.Exists(directoryPath))
            {
                Directory.CreateDirectory(directoryPath);
            }

            var testFile = Path.Combine(directoryPath, $".perm_test_{Guid.NewGuid():N}.tmp");
            using (var stream = File.Create(testFile, 1, FileOptions.DeleteOnClose))
            {
            }

            return true;
        }
        catch
        {
            return false;
        }
    }

    public static Dictionary<string, string> Read(string path)
    {
        var values = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
        if (!File.Exists(path))
        {
            return values;
        }

        foreach (var rawLine in File.ReadAllLines(path))
        {
            var line = rawLine.Trim();
            if (line.Length == 0 || line.StartsWith('#'))
            {
                continue;
            }

            var separator = line.IndexOf('=');
            if (separator <= 0)
            {
                continue;
            }

            var key = line[..separator].Trim();
            var value = line[(separator + 1)..].Trim();
            if (value.Length >= 2 &&
                ((value.StartsWith('"') && value.EndsWith('"')) ||
                 (value.StartsWith('\'') && value.EndsWith('\''))))
            {
                value = value[1..^1];
            }

            values[key] = value;
        }

        return values;
    }

    public static void Write(string path, IReadOnlyDictionary<string, string> values)
    {
        var dir = Path.GetDirectoryName(path);
        if (!string.IsNullOrEmpty(dir) && !Directory.Exists(dir))
        {
            Directory.CreateDirectory(dir);
        }

        var builder = new StringBuilder();
        builder.AppendLine("# Generated by ZktecoRelay.Manager. Do not commit this file.");

        foreach (var pair in values)
        {
            if (pair.Value.Contains('\n') || pair.Value.Contains('\r'))
            {
                throw new InvalidOperationException($"Environment value '{pair.Key}' cannot contain newlines.");
            }

            builder.Append(pair.Key).Append('=').AppendLine(pair.Value);
        }

        File.WriteAllText(path, builder.ToString(), new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));
    }
}
