using System.Text;

namespace ZktecoRelay.Manager;

internal static class EnvSettings
{
    public static Dictionary<string, string> Read(string path)
    {
        var values = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
        if (!File.Exists(path))
        {
            return values;
        }

        foreach (var rawLine in File.ReadAllLines(path))
        {
            var line = rawLine.Trim();
            if (line.Length == 0 || line.StartsWith('#'))
            {
                continue;
            }

            var separator = line.IndexOf('=');
            if (separator <= 0)
            {
                continue;
            }

            var key = line[..separator].Trim();
            var value = line[(separator + 1)..].Trim();
            if (value.Length >= 2 &&
                ((value.StartsWith('"') && value.EndsWith('"')) ||
                 (value.StartsWith('\'') && value.EndsWith('\''))))
            {
                value = value[1..^1];
            }

            values[key] = value;
        }

        return values;
    }

    public static void Write(string path, IReadOnlyDictionary<string, string> values)
    {
        var builder = new StringBuilder();
        builder.AppendLine("# Generated by ZktecoRelay.Manager. Do not commit this file.");

        foreach (var pair in values)
        {
            if (pair.Value.Contains('\n') || pair.Value.Contains('\r'))
            {
                throw new InvalidOperationException($"Environment value '{pair.Key}' cannot contain newlines.");
            }

            builder.Append(pair.Key).Append('=').AppendLine(pair.Value);
        }

        File.WriteAllText(path, builder.ToString(), new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));
    }
}
